#!/bin/bash
# individual_ipsets.sh

set -e

scriptversion=2025-02-19.15.54; # CST

# Copyright (C) 2025 - Mike's Tech Repair, All Rights Reserved.
# author: Michael Martinson
# contact: michael.martinson@mikestechrepair.com

help() {
	echo "Usage: $(basename $0)

	...
	...

	Example: bash $(basename $0)"
	exit 1
}

IPv4() {
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.alphastrike.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.arbor-observatory.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.binaryedge.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.bufferover.run.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.caida.org.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.censys.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.criminalip.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.cybergreen.net.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.dataplane.org.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.driftnet.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.erratasec.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.internet-census.org.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.internettl.org.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.intrinsec.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.inversepath.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.ipip.net.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.ipqualityscore.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.isi.edu.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.leakix.net.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.mpi-infmpg.de.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.ncsc.gov.uk.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.netsystemsresearch.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.onyphe.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.openportstats.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.paloaltonetworks.ca.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.quadmetrics.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.rapid7.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.recyber.net.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.scorecardresearch.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.securitytrails.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.shadowserver.org.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.shodan.io.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.spyse.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.stanford.edu.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.stretchoid.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.team-cymru.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.threatsinkhole.com.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.umich.edu.ipset
	ipset restore -file acknowledged_scanners_set/ipset_IPv4/nethash.unitasglobal.net.ipset
	return 0
}

IPv6() {
	ipset restore -file acknowledged_scanners_set/ipset_IPv6/nethash.censys.io.ip6set
	ipset restore -file acknowledged_scanners_set/ipset_IPv6/nethash.dataplane.org.ip6set
	ipset restore -file acknowledged_scanners_set/ipset_IPv6/nethash.driftnet.io.ip6set
	ipset restore -file acknowledged_scanners_set/ipset_IPv6/nethash.mpi-infmpg.de.ip6set
	return 0
}

# Recognise and Pars any command line arguments
for arg; do
	delim=""
	case "$arg" in
		--only4)					args="${args}-4 " ;;
		--only6)					args="${args}-6 " ;;
		--help)					args="${args}-h " ;;
		*)							[[ "${arg:0:1}" == "-" ]] || delim="\""
									args="${args}${delim}${arg}${delim} ";;
	esac
done
eval set -- "$args"

# Pars the command line arguments
while getopts "46h" Option; do
	case $Option in
		4) only4="yes" ;;
		6) only6="yes" ;;
		h) help ;;
		*) help ;;
	esac
done
shift "$(($OPTIND -1))"

if [ "$only4" = "yes" ] && [ "$only6" = "yes" ]; then
	echo "ERROR: If you would like to install both IPv4 and IPv6 filters, do not add cli arguments."
	exit 1
fi

# create_tables
if [[ "$only4" = "yes" ]]; then
	IPv4
	exit 0
elif [[ "$only6" = "yes" ]]; then
	IPv6
	exit 0
fi

# install the firewall tables and rules for both iptables and ip6tables
IPv4
IPv6

exit 0